### ISSUE TITLE
32-bit wine target

### ISSUE THREAD

**Issue by bernhardu** [JuliaComputing/gdb-solib-wine#2]
Hello, I attempted to take the 64-bit modifications as blueprint to make the same changes for 32-bit.
If I see it right wine references the thread local storage through `NtCurrentTeb()` which "simply" returns
the content of $gs_base + 0x30.
Unfortuantely I was not able to achive this for 32-bit with $fs_base + 0x18.
If I continue without this "little" detail, 9e1f54a1b580 seems like enough to make it work then.

**Comment by Keno** [comment]
If this is under rr, then you need to update https://github.com/rr-debugger/rr/tree/master/third-party/gdb with the 32bit-seg.xml file from upstream. Currently rr does not declare the fs/gsbase registers to gdb on 32bit, so they read as 0.

**Comment by bernhardu** [comment]
This was just a plain, from this repo built gdb directly attached to a wine process.
```
$ wine c:/windows/syswow64/notepad.exe

$ ps aux | grep notepad
bernhard 2156978  0.7  0.0 2717284 29188 pts/9   S+   11:22   0:00 c:/windows/syswow64/notepad.exe
$ gdb/gdb -q --pid 2156978
Attaching to process 2156978
Reading symbols from .../build-32/loader/wine-preloader...
0xf7fc2559 in __kernel_vsyscall ()
(gdb) print/x $fs
$1 = 0x63
(gdb) print/x $fs_base
$2 = void
(gdb) print/x $gs
$3 = 0x6b
(gdb) print/x $gs_base
$4 = void
(gdb)
```

Doing this with a 64-bit notepad it shows a proper value in `$gs_base`.

I experimented with doing similar things in rr as you did in [1a774d0b5946](https://github.com/rr-debugger/rr/commit/1a774d0b5946a19b291756092be699d5295c0dc1), but this did not help either, showed just a register count mismatch.
It looks like gdb does 32-bit segment regstiers just at some BSDs, e.g. `i386_target_description` called with `true`.

**Comment by bernhardu** [comment]
I got some more time and slightly remembered I saw in my debugging it used the "index" from $gs.
So I tried to replicate the gdb _magic_, but just using the "index" from $fs - and it seems to work as far as
my limited tests went. I did just a few tests running a 64-bit kernel, I fear that retrieving NtCurrentTeb
that way could possibly be limited to 64-bit kernel.
[32-bit-wine-target](https://github.com/bernhardu/gdb-solib-wine/tree/32-bit-wine-target)

Contains also a small change related to 2df093fba, otherwise it does not work for me anymore.

Just a small unrelated note: Would defaulting to `handle SIGUSR1 nostop` also be something to consider?

**Comment by Keno** [comment]
There's also the issue that the fs base conflicts with glibc, so whether the value points to the TIB or the glibc threading structures depends on which side of the wine syscall dispatch you're on. It might be easier to only handle the WoW64 case for now, in which case there is a full 64bit TIB in %gs that can be chained to the 32-bit one. In general, there's a question of how to represent that, since there's both 32 and 64 bit code in the process. I'm not sure whether GDB will want us to declare that as amd64 or i386 in that case.

**Comment by bernhardu** [comment]
Additionally my current version does not work with rr because at least it uses
the recorded pid instead of the current replaying pid,
and even then it should go through rr and not ptrace it directly.

For the double use of fs base I think I cannot follow. At least in my very limited test case it seems to return on both sides the same "index" and the same value in tib_addr:
```
warning: tib_addr=7ffc2000 via x86_linux_get_thread_area
(gdb) bt
#0  0xf7f16559 in __kernel_vsyscall ()
#1  0xf7d8f250 in __GI___select64 (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x9dfbac) at ../sysdeps/unix/sysv/linux/select.c:71
#2  0xf7d8f4f0 in __GI___select (nfds=0, readfds=0x0, writefds=0x0, exceptfds=0x0, timeout=0x9dfc38) at ../sysdeps/unix/sysv/linux/select.c:130
#3  0xf7c314fc in NtDelayExecution (alertable=0 '\000', timeout=0x9bfdc8) at .../wine-git/dlls/ntdll/unix/sync.c:1490
#4  0xf7c26359 in __wine_syscall_dispatcher () at .../wine-git/dlls/ntdll/unix/signal_i386.c:153
#5  0x00000000 in ?? ()
(gdb) print/x $fs
$1 = 0x63

# stepping out of NtDelayExecution and the __wine_syscall_dispatcher wrapper ...

(gdb) noshared
(gdb) shared
warning: tib_addr=7ffc2000 via x86_linux_get_thread_area
(gdb) bt
#0  0x7b0703a1 in Sleep@4 (timeout=60000) at .../wine-git/dlls/kernelbase/sync.c:269
#1  0x0045a4df in func_info () at .../wine-git/dlls/ntdll/tests/info.c:3545
#2  0x004daf8b in run_test (name=0x242797 "info") at .../wine-git/include/wine/test.h:612
#3  main (argc=2, argv=0x242720) at .../wine-git/include/wine/test.h:702
#4  0x004dab1f in mainCRTStartup () at .../wine-git/dlls/msvcrt/crt_main.c:58
#5  0x7b62def0 in WriteTapemark@16 () from .../wine-7.0-rc2/home/prefix/drive_c/windows/syswow64/kernel32.dll
#6  0x7bc57c27 in call_thread_func_wrapper () from .../wine-7.0-rc2/home/prefix/drive_c/windows/syswow64/ntdll.dll
#7  0x7bc582e0 in call_thread_func (entry=0x4daaa0 <mainCRTStartup>, arg=0x7ffd1000) at .../wine-git/dlls/ntdll/thread.c:225
#8  0x00000000 in ?? ()
(gdb) print/x $fs
$3 = 0x63
```
